### ISSUE TITLE
Remote I/O Error

### ISSUE THREAD

**Issue by jiamingbacon** [FaBoPlatform/FaBo9AXIS-MPU9250-Python#3]
```
Traceback (most recent call last):
  File "MPU_Pi3D.py", line 176, in <module>
    gyro = sensor.readGyro()
  File "/usr/local/lib/python2.7/dist-packages/FaBo9Axis_MPU9250/MPU9250.py", line 226, in readGyro
    data = bus.read_i2c_block_data(self.address, GYRO_OUT, 6)
IOError: [Errno 121] Remote I/O error
```

Hi,
This is the error I got when I ran the program. Have checked using that i2c-detect -y 1 shows my driver in 68.

**Comment by hackebike** [comment]
Did you solved the problem? Having the same issue.
