### ISSUE TITLE
External I/O error

### ISSUE THREAD

**Issue by Cristhiandavx** [FaBoPlatform/FaBo9AXIS-MPU9250-Python#6]
I hope I can find some help whit this error.
Whenever I run my program on the Terminal of my Raspberry Pi Model A+ I get this:

`Traceback (most recent call last):
  File "mpu9250_program.py", line 6, in <module>
    mpu9250 = FaBo9Axis_MPU9250.MPU9250()
  File "/usr/local/lib/python2.7/dist-packages/FaBo9Axis_MPU9250/MPU9250.py", line 103, in __init__
    self.configAK8963(AK8963_MODE_C8HZ, AK8963_BIT_16)
  File "/usr/local/lib/python2.7/dist-packages/FaBo9Axis_MPU9250/MPU9250.py", line 169, in configAK8963
    bus.write_byte_data(AK8963_SLAVE_ADDRESS, AK8963_CNTL1, 0x00)
IOError: [Errno 121] Remote I/O error`

I was able to run correctly the first time, but after a while of not using nor modifying the program this error appears.

Are there any suggestions for solving this?

**Comment by hackebike** [comment]
same, did you solved it ?

**Comment by klattimer** [comment]
Same on a pi-nano-w
